version: '3.8'

services:

  # DuckDB service with Python environment
  duckdb-service:
    build:
      context: .
      dockerfile: Dockerfile.duckdb
    container_name: duckdb-service
    ports:
      - "8888:8888"  # Jupyter notebook
      - "5000:5000"  # Flask API
    volumes:
      - ./data:/app/data:ro  # Mount CSV data as read-only
    environment:
      - LITELLM_API_BASE=https://litellm.prod-ai.riotgames.io/
      - LITELLM_MODEL=gpt-4-1
      - LITELLM_API_KEY=sk-RywMmYwRHCdna6UiKhiGtw
    restart: unless-stopped
    networks:
      - ai_network

volumes:
  ollama_data:

networks:
  ai_network:
    driver: bridge
